# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cars_data_pb2 as cars__data__pb2


class CarServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCar = channel.unary_unary(
                '/CarService/GetCar',
                request_serializer=cars__data__pb2.CarRequest.SerializeToString,
                response_deserializer=cars__data__pb2.CarResponse.FromString,
                )


class CarServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CarServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCar': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCar,
                    request_deserializer=cars__data__pb2.CarRequest.FromString,
                    response_serializer=cars__data__pb2.CarResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CarService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CarService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CarService/GetCar',
            cars__data__pb2.CarRequest.SerializeToString,
            cars__data__pb2.CarResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
