# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cars_data.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63\x61rs_data.proto\"\x18\n\nCarRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"B\n\x0b\x43\x61rResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x63\x61r_name\x18\x02 \x01(\t\x12\x15\n\rPresent_Price\x18\x03 \x01(\t21\n\nCarService\x12#\n\x06GetCar\x12\x0b.CarRequest\x1a\x0c.CarResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cars_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CARREQUEST']._serialized_start=19
  _globals['_CARREQUEST']._serialized_end=43
  _globals['_CARRESPONSE']._serialized_start=45
  _globals['_CARRESPONSE']._serialized_end=111
  _globals['_CARSERVICE']._serialized_start=113
  _globals['_CARSERVICE']._serialized_end=162
# @@protoc_insertion_point(module_scope)
